//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EazyWizy.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EazyWizyEntities : DbContext
    {
        public EazyWizyEntities()
            : base("name=EazyWizyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<TopMenu> sp_Select_GetMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopMenu>("sp_Select_GetMenu");
        }
    
        public virtual ObjectResult<LHSMenu> sp_Select_GetLHSMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LHSMenu>("sp_Select_GetLHSMenu");
        }
    
        public virtual ObjectResult<LHSSubMenuBrand> sp_Select_GetSubMenuBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LHSSubMenuBrand>("sp_Select_GetSubMenuBrand");
        }
    
        public virtual ObjectResult<LHSBrandFilter> sp_Select_GetSubMenuBrandFilter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LHSBrandFilter>("sp_Select_GetSubMenuBrandFilter");
        }
    }
}
