//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EazyWizy.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EazyWizyEntities : DbContext
    {
        public EazyWizyEntities()
            : base("name=EazyWizyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<TopMenu> sp_Select_GetMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopMenu>("sp_Select_GetMenu");
        }
    
        public virtual ObjectResult<LHSMenu> sp_Select_GetLHSMenu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LHSMenu>("sp_Select_GetLHSMenu");
        }
    
        public virtual ObjectResult<LHSSubMenuBrand> sp_Select_GetSubMenuBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LHSSubMenuBrand>("sp_Select_GetSubMenuBrand");
        }
    
        public virtual ObjectResult<LHSBrandFilter> sp_Select_GetSubMenuBrandFilter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LHSBrandFilter>("sp_Select_GetSubMenuBrandFilter");
        }
    
        public virtual ObjectResult<Product> GetAllProduct(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("GetAllProduct", product_idParameter);
        }
    
        public virtual ObjectResult<ProductCategory> GetAllProductCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductCategory>("GetAllProductCategory");
        }
    
        public virtual ObjectResult<ProductCategory> GetChieldProductCategorys(string parent_product_type_code)
        {
            var parent_product_type_codeParameter = parent_product_type_code != null ?
                new ObjectParameter("parent_product_type_code", parent_product_type_code) :
                new ObjectParameter("parent_product_type_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductCategory>("GetChieldProductCategorys", parent_product_type_codeParameter);
        }
    
        public virtual ObjectResult<Product> GetProduct(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("GetProduct", product_idParameter);
        }
    
        public virtual ObjectResult<Product> GetProductByCategory(string product_type_code)
        {
            var product_type_codeParameter = product_type_code != null ?
                new ObjectParameter("product_type_code", product_type_code) :
                new ObjectParameter("product_type_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Product>("GetProductByCategory", product_type_codeParameter);
        }
    
        public virtual ObjectResult<ProductCategory> GetProductCategory(string product_type_code)
        {
            var product_type_codeParameter = product_type_code != null ?
                new ObjectParameter("product_type_code", product_type_code) :
                new ObjectParameter("product_type_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProductCategory>("GetProductCategory", product_type_codeParameter);
        }
    }
}
