//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EazyWizy.Domain.Entities
{
    using System;
    
    public partial class LHSSubMenuBrand
    {
        public int IdBrand { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    }
}
