//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EazyWizy.Domain.Entities
{
    using System;
    
    public partial class ProductCategory
    {
        public string product_type_code { get; set; }
        public string parent_product_type_code { get; set; }
        public string product_type_description { get; set; }
        public string productTypeImageName { get; set; }
    }
}
