//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EazyWizy.Domain.Entities
{
    using System;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public string TypeCode { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string ImageName { get; set; }
        public string Description { get; set; }
        public string OtherProductDetails { get; set; }
    }
}
