//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EazyWizy.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EazyWizy.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to key \&quot;{0}\&quot; in root config file is not allowed..
        /// </summary>
        public static string Error_AccessToKeyInRootConfigNotAllowed {
            get {
                return ResourceManager.GetString("Error_AccessToKeyInRootConfigNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both category and version must be provided..
        /// </summary>
        public static string Error_CategoryAndVersionRequired {
            get {
                return ResourceManager.GetString("Error_CategoryAndVersionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category, name and version must be provided..
        /// </summary>
        public static string Error_CategoryVersionNameRequired {
            get {
                return ResourceManager.GetString("Error_CategoryVersionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty in PTConfigConnectionString.
        /// </summary>
        public static string Error_EmptyPasswordInPTConfigConnectionString {
            get {
                return ResourceManager.GetString("Error_EmptyPasswordInPTConfigConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is empty in PTConfigConnectionString.
        /// </summary>
        public static string Error_EmptyUserIDInPTConfigConnectionString {
            get {
                return ResourceManager.GetString("Error_EmptyUserIDInPTConfigConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection string found for name &apos;{0}&apos; and version &apos;{1}&apos;..
        /// </summary>
        public static string Error_NoConnectionStringFoundForNameAndVersion {
            get {
                return ResourceManager.GetString("Error_NoConnectionStringFoundForNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No XML found for type &apos;{0}&apos;, name &apos;{1}&apos; and version &apos;{2}&apos;..
        /// </summary>
        public static string Error_NoXmlFoundForCategoryNameVersion {
            get {
                return ResourceManager.GetString("Error_NoXmlFoundForCategoryNameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found XML in CACHE for type &apos;{0}&apos;, name &apos;{1}&apos; and version &apos;{2}&apos;..
        /// </summary>
        public static string Trace_FoundXmlInCache {
            get {
                return ResourceManager.GetString("Trace_FoundXmlInCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting config root path from default config file....
        /// </summary>
        public static string Trace_GettingConfigRootPathFromConfigFile {
            get {
                return ResourceManager.GetString("Trace_GettingConfigRootPathFromConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded XML from DATABASE for type &apos;{0}&apos;, name &apos;{1}&apos; and version &apos;{2}&apos;..
        /// </summary>
        public static string Trace_LoadedXmlFromDatabase {
            get {
                return ResourceManager.GetString("Trace_LoadedXmlFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading XML from DATABASE for type &apos;{0}&apos;, name &apos;{1}&apos; and version &apos;{2}&apos;....
        /// </summary>
        public static string Trace_LoadingXmlFromDatabase {
            get {
                return ResourceManager.GetString("Trace_LoadingXmlFromDatabase", resourceCulture);
            }
        }
    }
}
