USE EAZYWIZY

TRUNCATE TABLE TOPMENU 

INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('HOME','1',GETDATE(),NULL,NULL,1,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Last Buy','1',GETDATE(),NULL,NULL,2,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Track Order','1',GETDATE(),NULL,NULL,3,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Sign Up','1',GETDATE(),NULL,NULL,4,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Customer Support','1',GETDATE(),NULL,NULL,5,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Log Out','1',GETDATE(),NULL,NULL,6,1)