USE EAZYWIZY

TRUNCATE TABLE TOPMENU 

INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Home','1',GETDATE(),NULL,NULL,1,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Last Buy','1',GETDATE(),NULL,NULL,2,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Track Order','1',GETDATE(),NULL,NULL,3,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Sign Up','1',GETDATE(),NULL,NULL,4,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Customer Support','1',GETDATE(),NULL,NULL,5,1)
INSERT INTO TOPMENU (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Log Out','1',GETDATE(),NULL,NULL,6,1)


TRUNCATE TABLE LHSMenu 

INSERT INTO LHSMenu (Name,CreatedBy,Image,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Categories','1','category.png',GETDATE(),NULL,NULL,1,1)
INSERT INTO LHSMenu (Name,CreatedBy,Image,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Brand','1','brand.png',GETDATE(),NULL,NULL,2,1)
INSERT INTO LHSMenu (Name,CreatedBy,Image,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Exotic Fruits','1','fruits.png',GETDATE(),NULL,NULL,3,1)
INSERT INTO LHSMenu (Name,CreatedBy,Image,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Exotic Vegetables','1','Vegetables.png',GETDATE(),NULL,NULL,4,1)
INSERT INTO LHSMenu (Name,CreatedBy,Image,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Stationary','1','Stationary.png',GETDATE(),NULL,NULL,5,1)


TRUNCATE TABLE BRANDMASTER 
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('ITC','1',GETDATE(),NULL,NULL,1,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Hul','1',GETDATE(),NULL,NULL,2,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,3,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Fena','1',GETDATE(),NULL,NULL,4,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,5,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,6,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Fena','1',GETDATE(),NULL,NULL,7,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,8,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,9,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('ITC','1',GETDATE(),NULL,NULL,10,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Hul','1',GETDATE(),NULL,NULL,11,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,12,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Fena','1',GETDATE(),NULL,NULL,13,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,14,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,15,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,16,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Fena','1',GETDATE(),NULL,NULL,17,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,18,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,19,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Fena','1',GETDATE(),NULL,NULL,20,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,21,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,22,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Fena','1',GETDATE(),NULL,NULL,23,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,24,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,25,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,26,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,27,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Fena','1',GETDATE(),NULL,NULL,28,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Emami','1',GETDATE(),NULL,NULL,29,1)
INSERT INTO BRANDMASTER (Name,CreatedBy,CreatedDate,UpdatedBy,UpdatedTime,SortedNumber,IsActive) VALUES ('Tata','1',GETDATE(),NULL,NULL,30,1)