USE [master]
GO

/****** Object:  Database [EazyWizy]    Script Date: 04/10/2014 20:39:28 ******/
CREATE DATABASE [EazyWizy] ON  PRIMARY 
( NAME = N'EazyWizy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\EazyWizy.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EazyWizy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\EazyWizy_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EazyWizy] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EazyWizy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EazyWizy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EazyWizy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EazyWizy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EazyWizy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EazyWizy] SET ARITHABORT OFF 
GO

ALTER DATABASE [EazyWizy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EazyWizy] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EazyWizy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EazyWizy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EazyWizy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EazyWizy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EazyWizy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EazyWizy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EazyWizy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EazyWizy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EazyWizy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EazyWizy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EazyWizy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EazyWizy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EazyWizy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EazyWizy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EazyWizy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EazyWizy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EazyWizy] SET  READ_WRITE 
GO

ALTER DATABASE [EazyWizy] SET RECOVERY FULL 
GO

ALTER DATABASE [EazyWizy] SET  MULTI_USER 
GO

ALTER DATABASE [EazyWizy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EazyWizy] SET DB_CHAINING OFF 
GO

