//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EFData
{
    using System;
    
    public partial class LHSMenu
    {
        public int IdLHSMenu { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    }
}
